### ISSUE TITLE
Not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by kaykujo** [MalaysiaPrayerTimes/server#1]
Assalamualaikum,

I am trying to use your new API in an Ionic project. I get an error when opening the app in actual device and live preview. However, it works if i type the URL directly into the browser's address bar.

```
XMLHttpRequest cannot load https://mpt.i906.my/api/prayer/3.10231231,101.231233. Origin http://localhost:8100 is not allowed by Access-Control-Allow-Origin.
```

```
{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null
],"url":"https://mpt.i906.my/api/prayer/3.10231231,101.231233","headers":{"Accept":"application/json, text/plain, */*"}},"sta
tusText":""}
```

Can you please help me.

Thanks.

**Comment by i906** [comment]
Waalaikumussalam @kaykujo,

The issue has been fixed and deployed. You can try again.

Thanks.

**Comment by kaykujo** [comment]
Thank you so much, I will try and update you later =)

**Comment by kaykujo** [comment]
Assalamualaikum,

I am able to use it for a few times until this issue occured again.

Thanks.

**Comment by kaykujo** [comment]
Assalamualaikum,

It's working again now. Sorry for the trouble.

Thanks.

EDIT : Opps sorry, i am getting the error again. Do you have a limit on how frequent I can hit the API?

**Comment by kaykujo** [comment]
Assalamualaikum, @i906 can you please look into this. Thanks.

**Comment by i906** [comment]
@kaykujo I have tested again at [test-cors.org](http://test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fmpt.i906.my%2Fapi%2Fprayer%2F3.10231231%2C101.231233&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) and it worked fine.
